config/routes.rb
Rails.application.routes.draw do
  resources :vacancies, except: [:show]
  resources :parkings
  root 'dashboard#index'
  get    '/login', to: 'auth#index',   as: nil
  post   '/login', to: 'auth#create',  as: :login
  delete '/login', to: 'auth#destroy', as: :logout
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  include ApplicationHelper

  def index
    @title = "Página de login - Dashboard Administrador"

    response = make_api_request(:get, true, 'current_administrator')    
    valid = response.code == '200'

    if valid
      redirect_to root_path
    else
      render :index
    end
  end

  def create
    params = new_login_params
    params.delete(:authenticity_token)

    body = { 'administrator' => params }

    response = make_api_request(:post, false, 'login', body)
    success = response.code == '200'

    if success
      cookies[:auth_token] = response.header['Authorization']

      flash[:notice] = 'Login realizado com sucesso.'
      redirect_to root_path
    else
      message = response.body

      flash[:alert] = "Login falhou: #{message}"
      redirect_to root_path
    end
  end

  def destroy
    response = make_api_request(:delete, true, 'logout')
    success = response.code == '200'

    if success
      redirect_to "/login"
    end
  end

  private

  def new_login_params
    params.permit(:authenticity_token, :email, :password)
  end
end

app/controllers/concerns/token_validation.rb
module TokenValidation
    extend ActiveSupport::Concern
    include ApplicationHelper
  
    included do
      before_action :validate_token
    end
  
    private
  
    def validate_token
      response = make_api_request(:get, true, 'current_administrator')

      valid = response.code == '200'
      message = response.body

      if not valid
        flash[:alert] = "Token inválido: #{message}"
        redirect_to '/login'
      end
    end
  end
  

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include TokenValidation
  include ApplicationHelper

  def index
    @title = "Página inicial - Dashboard Administrador"
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  include TokenValidation
  include ApplicationHelper
  layout 'dashboard'

  # GET /parkings
  def index
    @title = "Estacionamentos - Dashboard Administrador"

    response = make_api_request(:get, true, 'parkings')
    @parkings = JSON.parse(response.body, symbolize_names: true)
  end

  # GET /parkings/1
  def show
    response = make_api_request(:get, true, "parkings/#{parking_params[:id]}")
    @parking = JSON.parse(response.body, symbolize_names: true)
    
    @title = "Estacionamento #{@parking[:name]} - Dashboard Administrador"
  end

  # GET /parkings/new
  def new
    @title = "Adicionar novo estacionamento - Dashboard Administrador"

    @parking = {}
  end

  # GET /parkings/1/edit
  def edit
    response = make_api_request(:get, true, "parkings/#{parking_params[:id]}")
    @parking = JSON.parse(response.body, symbolize_names: true)

    @title = "Editando estacionamento #{@parking[:name]} - Dashboard Administrador"
  end

  # POST /parkings
  def create
    body = { 'parking' => parking_params }

    response = make_api_request(:post, true, "parkings", body)
    created = response.code == '201'

    if created
      flash[:notice] = "Estacionamento criado com sucesso."
      redirect_to parkings_path
    else
      flash[:alert] = "Erro ao cadastrar estacionamento."
    end
  end

  # PATCH/PUT /parkings/1
  def update
    params = parking_params
    params.delete(:id)
    body = { 'parking' => params }

    response = make_api_request(:put, true, "parkings/#{parking_params[:id]}", body)
    updated = response.code == '200'

    if updated
      flash[:notice] = "Estacionamento atualizado com sucesso."
      redirect_to parkings_path
    else
      flash[:alert] = "Erro ao atualizar estacionamento."
    end
  end

  # DELETE /parkings/1
  def destroy
    response = make_api_request(:delete, true, "parkings/#{parking_params[:id]}")
    deleted = response.code == '200'

    if deleted
      flash[:notice] = "Estacionamento removido com sucesso."
      redirect_to parkings_path
    else
      flash[:alert] = "Erro ao deletar estacionamento."
    end
  end

  private

  def parking_params
    params.permit(:id, :name, :address, :opening_time, :closing_time, :cost_per_hour)
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  include TokenValidation
  include ApplicationHelper
  layout 'dashboard'

  # GET /vacancies
  def index
    @title = "Vagas - Dashboard Administrador"
    @vacancies = {}

    response = make_api_request(:get, true, 'parkings')
    @parkings = JSON.parse(response.body, symbolize_names: true)

    parking_id = vacancy_params[:parking_id]
    if parking_id
      @current_parking = @parkings.find { |item| item[:id] == parking_id.to_i }

      response = make_api_request(:get, true, "vacancies?parking_id=#{parking_id}")
      @vacancies = JSON.parse(response.body, symbolize_names: true)
    end
  end

  # GET /vacancies/new
  def new
    @title = "Adicionar novo vaga - Dashboard Administrador"

    @vacancy = vacancy_params
  end

  # GET /vacancies/1/edit
  def edit
    @title = "Editando vaga - Dashboard Administrador"

    params = vacancy_params

    response = make_api_request(:get, true, "vacancies?parking_id=#{params[:parking_id]}")
    @vacancies = JSON.parse(response.body, symbolize_names: true)

    @vacancy = @vacancies.find { |item| item[:id] == params[:id].to_i }
  end

  # POST /vacancies
  def create
    params = vacancy_params
    body = { 'vacancy' => params }
    parking_id = params[:parking_id]

    response = make_api_request(:post, true, "vacancies", body)
    created = response.code == '201'

    if created
      flash[:notice] = "Vaga criada com sucesso."
      redirect_to "/vacancies?parking_id=#{parking_id}"
    else
      flash[:alert] = "Erro ao cadastrar vaga."
    end
  end

  # PATCH/PUT /vacancies/1
  def update
    params = vacancy_params
    id = params[:id]
    params.delete(:id)
    body = { 'vacancy' => params }

    response = make_api_request(:put, true, "vacancies/#{id}", body)
    updated = response.code == '200'

    if updated
      flash[:notice] = "Vaga atualizada com sucesso."
      redirect_to "/vacancies?parking_id=#{params[:parking_id]}"
    else
      flash[:alert] = "Erro ao atualizar vaga."
    end
  end

  # DELETE /vacancies/1
  def destroy
    response = make_api_request(:delete, true, "vacancies/#{vacancy_params[:id]}")
    deleted = response.code == '200'

    if deleted
      flash[:notice] = "Vaga removida com sucesso."
      redirect_to "/vacancies?parking_id=#{params[:parking_id]}"
    else
      flash[:alert] = "Erro ao deletar vaga."
    end
  end

  private

  def vacancy_params
    params.permit(:id, :parking_id, :code, :kind)
  end
end

app/helpers/application_helper.rb
require 'net/http'
require 'json'

module ApplicationHelper
  def make_api_request(method, auth, route, body = {})
    api_url = 'http://localhost:3000'
    api_token = cookies[:auth_token]

    uri = URI("#{api_url}/#{route}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme == 'https'

    request = case method
              when :get
                Net::HTTP::Get.new(uri.request_uri)
              when :post
                Net::HTTP::Post.new(uri.request_uri)
              when :put
                Net::HTTP::Put.new(uri.request_uri)
              when :delete
                Net::HTTP::Delete.new(uri.request_uri)
              else
                raise ArgumentError, "Invalid method: #{method}"
              end

    if auth
      request['Authorization'] = api_token
    end
    request['Content-Type'] = 'application/json'
    request.body = body.to_json

    response = http.request(request)

    return response
  rescue StandardError => e
    handle_api_error(e.message)
  end

  private

  def handle_api_error(error_message)
    puts error_message
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
  def format_time(time_string)
    return if not time_string

    time = Time.parse(time_string)
    time.strftime("%H:%M")
  end

  def format_cost(cost)
    number_with_precision(cost, precision: 2)
  end

  def format_date(date_string)
    date = Date.parse(date_string)
    date.strftime("%d/%m/%Y")
  end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/dashboard/index.html.erb
<section class="container d-flex justify-content-center align-items-center h-100 w-100">
  <div class="row text-center">
    <div class="col justify-content-center">
      <%= image_tag "welcome-banner.svg", class: "welcome-banner" %>
      <h3>Seja bem-vindo(a), administrador(a).</h3>
    </div>
  </div>
</section>

app/views/layouts/_flash-messages.html.erb
<% if flash.notice %>
  <div class="alert alert-info" role="alert">
    <%= flash.notice %>
  </div>
<% end %>

<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow px-4">
  <div class="container-fluid">
    <!-- Informações do usuário -->
    <%= link_to root_path do %>
      <%= image_tag "logo.png", class: "logo" %>
    <% end %>
    <!-- Botão de logout -->
    <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-danger" %>
  </div>
</nav>

app/views/layouts/_public-navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light shadow px-4">
  <div class="container-fluid justify-content-center">
    <%= image_tag "logo.png", class: "logo" %>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="nav flex-column py-5">
  <li class="nav-item">
    <a id="parkings" class="nav-link d-flex align-items-center" href="/parkings">
      <i class="fas fa-parking icon"></i>
      Estacionamentos
    </a>
  </li>

  <li class="nav-item">
    <a id="vacancies" class="nav-link d-flex align-items-center" href="/vacancies">
      <i class="fas fa-car icon"></i>
      Vagas
    </a>
  </li>
</ul>

<script type="text/javascript">
  window.onload = () => {
    let navLink = document.getElementById("<%= controller_name %>");
    navLink.classList.add('active');
  };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "AdministratorFrontendSei" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/public-navbar' %>
    <%= render 'layouts/flash-messages' %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "AdministratorFrontendSei" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <div class="container-fluid h-100">
      <div class="row h-100">
        <div class="col-2 sidebar px-0 d-flex flex-column dark-background">
          <%= render 'layouts/sidebar' %>
        </div>

        <div class="col-10 px-0 d-flex flex-column" style="height: inherit;">
          <%= render 'layouts/navbar' %>

          <div class="content flex-grow-1 overflow-auto">
            <%= render 'layouts/flash-messages' %>

            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/layouts/shared/_card.html.erb
<div class="card border-0 shadow mb-3">
  <div class="card-body p-3">
    <%= yield %>
  </div>
</div>

app/views/layouts/shared/_resource-actions.html.erb
<div class="mt-3 d-flex" aria-label="Ações">
  <% if defined?(show_link) %>
    <%= link_to "Ver", show_link, class: "btn success-background mx-1" %>
  <% end %>

  <% if defined?(edit_link) %>
    <%= link_to "Editar", edit_link, class: "btn primary-variant-background mx-1" %>
  <% end %>

  <% if defined?(delete_link) %>
    <%= button_to "Apagar", delete_link, class: "btn danger-background mx-1", method: :delete %>
  <% end %>
</div>

app/views/parkings/_form.html.erb
<%= form_with(url: "/parkings/#{@parking[:id]}", method: :post, local: true, authenticity_token: true) do |form| %>
  <% if action_name == 'edit' %>
    <%= hidden_field_tag "_method", "PUT" %>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Nome do Estacionamento" %>
    <%= form.text_field :name, class: "form-control", value: @parking[:name] %>
  </div>

  <div class="form-group">
    <%= form.label :address, "Endereço" %>
    <%= form.text_field :address, class: "form-control", value: @parking[:address] %>
  </div>

  <div class="form-group">
    <%= form.label :opening_time, "Horário de Abertura" %>
    <%= form.time_field :opening_time, class: "form-control", value: format_time(@parking[:opening_time]) %>
  </div>

  <div class="form-group">
    <%= form.label :closing_time, "Horário de Fechamento" %>
    <%= form.time_field :closing_time, class: "form-control", value: format_time(@parking[:closing_time]) %>
  </div>

  <div class="form-group">
    <%= form.label :cost_per_hour, "Custo por Hora" %>
    <%= form.number_field :cost_per_hour, class: "form-control", value: @parking[:cost_per_hour] %>
  </div>

  <%= form.submit "Salvar", class: "btn success-background mt-3" %>
<% end %>

app/views/parkings/_parking.html.erb
<%= render layout: 'layouts/shared/card' do %>
  <h3><%= parking[:name] %></h3>
  <p class="mb-0"><strong>Endereço:</strong> <%= parking[:address] %></p>
  <p class="mb-0"><strong>Horário de abertura:</strong> <%= format_time(parking[:opening_time]) %></p>
  <p class="mb-0"><strong>Horário de fechamento:</strong> <%= format_time(parking[:closing_time]) %></p>
  <p class="mb-0"><strong>Custo por hora:</strong> <%= format_cost(parking[:cost_per_hour]) %></p>

  <%= render partial: 'layouts/shared/resource-actions',
             locals: {
               show_link: "/parkings/#{parking[:id]}",
               edit_link: "/parkings/#{parking[:id]}/edit",
               delete_link: "/parkings/#{parking[:id]}"
             } %>
<% end %>

app/views/parkings/edit.html.erb
<div class="page-title mb-3">
  <h1>Edite estacionamento</h1>

  <%= link_to "Voltar para estacionamentos", parkings_path, class: "btn danger-background" %>
</div>

<%= render layout: 'layouts/shared/card' do %>
  <%= render "form", parking: @parking %>
<% end %>

app/views/parkings/index.html.erb
<div class="page-title mb-3">
  <h1>Estacionamentos</h1> 

  <%= link_to "Adicionar", new_parking_path, class: 'btn secondary-background' %>
</div>

<div id="parkings">
  <% if not @parkings.empty? %>
    <% @parkings.each do |parking| %>
      <%= render 'parkings/parking', parking: parking %>
    <% end %>

  <% else %>
    <%= render layout: 'layouts/shared/card' do %>
      <p class="p-3">Nenhum estacionamento foi encontrado.</p>
    <% end %>
  <% end %>
</div>

app/views/parkings/new.html.erb
<div class="page-title mb-3">
  <h1>Novo estacionamento</h1>

  <%= link_to "Voltar para estacionamentos", parkings_path, class: "btn danger-background" %>
</div>

<%= render layout: 'layouts/shared/card' do %>
  <%= render "form" %>
<% end %>

app/views/parkings/show.html.erb
<div class="page-title mb-3">
  <h3><%= @parking[:name] %></h3>

  <%= link_to "Voltar para estacionamentos", parkings_path, class: "btn danger-background" %>
</div>

<%= render layout: 'layouts/shared/card' do %>
  <p class="mb-0"><strong>Endereço:</strong> <%= @parking[:address] %></p>
  <p class="mb-0"><strong>Horário de abertura:</strong> <%= format_time(@parking[:opening_time]) %></p>
  <p class="mb-0"><strong>Horário de fechamento:</strong> <%= format_time(@parking[:closing_time]) %></p>
  <p class="mb-0"><strong>Custo por hora:</strong> <%= format_cost(@parking[:cost_per_hour]) %></p>
  <p class="mb-0"><strong>Criado em:</strong> <%= format_date(@parking[:created_at]) %></p>
  <p class="mb-0"><strong>Última edição em:</strong> <%= format_date(@parking[:updated_at]) %></p>
  
  <%# render partial: 'layouts/shared/resource-actions',
             locals: {
             } %>
<% end %>

app/views/vacancies/_form.html.erb
<%= form_with(url: "/vacancies/#{@vacancy[:id]}", method: :post, local: true, authenticity_token: true) do |form| %>
  <% if action_name == 'edit' %>
    <%= hidden_field_tag "_method", "PUT" %>
  <% end %>

  <%= hidden_field_tag :parking_id, @vacancy[:parking_id] %>

  <div class="form-group">
    <%= form.label :code, "Código" %>
    <%= form.text_field :code, class: "form-control", value: @vacancy[:code] %>
  </div>

  <div class="form-group">
    <%= form.label :kind, "Tipo" %>
    <%= select_tag :kind, options_for_select({
      'Small' => 'small',
      'Medium' => 'medium',
      'Large' => 'large',
      'Special' => 'special',
      'Motorcycle' => 'motorcycle'
    }), class: "form-control", value: @vacancy[:kind] %>
  </div>

  <%= form.submit "Salvar", class: "btn success-background mt-3" %>
<% end %>

app/views/vacancies/_vacancy.html.erb
<%= render layout: 'layouts/shared/card' do %>
  <p class="mb-0"><strong>Código:</strong> <%= vacancy[:code] %></p>
  <p class="mb-0"><strong>Tipo:</strong> <%= vacancy[:kind] %></p>

  <%= render partial: 'layouts/shared/resource-actions',
             locals: {
               edit_link: "/vacancies/#{vacancy[:id]}/edit?parking_id=#{vacancy[:parking_id]}",
               delete_link: "/vacancies/#{vacancy[:id]}?parking_id=#{vacancy[:parking_id]}"
             } %>
<% end %>

app/views/vacancies/edit.html.erb
<div class="page-title mb-3">
  <h1>Edite vaga</h1>

  <%= link_to "Voltar para vagas", "/vacancies?parking_id=#{@vacancy[:parking_id]}", class: "btn danger-background" %>
</div>

<%= render layout: 'layouts/shared/card' do %>
  <%= render "form", vacancy: @vacancy %>
<% end %>

app/views/vacancies/index.html.erb
<div class="page-title mb-3">
  <h1>Vagas</h1> 

  <% if @current_parking %>
    <%= link_to "Adicionar", "/vacancies/new?parking_id=#{@current_parking[:id]}", class: 'btn secondary-background' %>
  <% end %>
</div>

<%= select_tag 'parking_dropdown', options_for_select(@parkings.map { |parking| [parking[:name], parking[:id]] }), prompt: 'Selecione um estacionamento', class: 'form-control mb-3' %>

<% if @current_parking %>
  <h4 class="mb-3">Vagas de: <%= @current_parking[:name] %></h4>
<% end %>

<div id="vacancies">
  <% if not @vacancies.empty? %>
    <div class="row">
      <% @vacancies.each do |vacancy| %>
        <div class="col-4">
          <%= render 'vacancies/vacancy', vacancy: vacancy %>
        </div>
      <% end %>
    </div>

  <% else %>
    <%= render layout: 'layouts/shared/card' do %>
      <p class="mb-0 p-3">Nenhuma vaga foi encontrado.</p>
    <% end %>
  <% end %>
</div>

<script>
  document.getElementById('parking_dropdown').addEventListener('change', function() {
    var selectedParkingId = this.value;
    if (selectedParkingId) {
      window.location.href = '/vacancies?parking_id=' + selectedParkingId;
    }
  });
</script>

app/views/vacancies/new.html.erb
<div class="page-title mb-3">
  <h1>Nova vaga</h1>

  <%= link_to "Voltar para vagas", "/vacancies?parking_id=#{@vacancy[:parking_id]}", class: "btn danger-background" %>
</div>

<%= render layout: 'layouts/shared/card' do %>
  <%= render "form" %>
<% end %>

app/views/vacancies/show.html.erb
<div class="page-title mb-3">
  <h3><%= @parking[:name] %></h3>

  <%= link_to "Voltar para vagas", vacancies_path, parking_id: @vacancy[:parking_id], class: "btn danger-background" %>
</div>